---
- name: install unattended-upgrades
  become: yes
  apt:
    pkg: unattended-upgrades
    state: present
    cache_valid_time: 3600 # Replace with a var?
    update_cache: true

- name: Disallow password authentication
  become: yes
  lineinfile: dest=/etc/ssh/sshd_config
              regexp="^PasswordAuthentication"
              line="PasswordAuthentication no"
              state=present
  notify: Restart ssh

- name: Disallow root SSH access
  become: yes
  lineinfile: dest=/etc/ssh/sshd_config
              regexp="^PermitRootLogin"
              line="PermitRootLogin no"
              state=present
  notify: Restart ssh

