---
- name: install req packages
  become: yes
  apt:
    name: "{{ debian_req_packages }}"
    update_cache: true

- name: Disallow password authentication
  become: yes
  lineinfile: 
    dest: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"
    state: present
  notify: Restart ssh

- name: Disallow root SSH access
  become: yes
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin no"
    state: present
  notify: Restart ssh

- name: Deploy dotfiles
  git:
    repo: https://github.com/jdheyburn/dotfiles.git
    dest: /home/jdheyburn/dotfiles
